import React from "react";
import { Link } from "react-router-dom";

const Home = () => {
  return (
    <div className="dhiwise-navigation">
      <h1>Homepage</h1>
      <p className="headline">
        This project was generated By{" "}
        <a href="https://www.dhiwise.com">Dhiwise</a>. Quickly use below links
        to navigate through all pages.
      </p>
      <ul>
        <li>
          <Link to="/independencethree">IndependenceThree</Link>
        </li>
        <li>
          <Link to="/contact">Contact</Link>
        </li>
        <li>
          <Link to="/protohistoryfour">ProtohistoryFour</Link>
        </li>
        <li>
          <Link to="/after1945one">After1945One</Link>
        </li>
        <li>
          <Link to="/frenchdominationtwo">FrenchDominationTwo</Link>
        </li>
        <li>
          <Link to="/frenchdominationone">FrenchDominationOne</Link>
        </li>
        <li>
          <Link to="/frenchdominationfour">FrenchDominationFour</Link>
        </li>
        <li>
          <Link to="/prehistorictwo">PrehistoricTwo</Link>
        </li>
        <li>
          <Link to="/independencetwo">IndependenceTwo</Link>
        </li>
        <li>
          <Link to="/prehistoricthree">PrehistoricThree</Link>
        </li>
        <li>
          <Link to="/timeline">Timeline</Link>
        </li>
        <li>
          <Link to="/website">Website</Link>
        </li>
        <li>
          <Link to="/independenceone">IndependenceOne</Link>
        </li>
        <li>
          <Link to="/chinesedominationone">ChineseDominationOne</Link>
        </li>
        <li>
          <Link to="/protohistorythree">ProtohistoryThree</Link>
        </li>
        <li>
          <Link to="/chinesedominationthree">ChineseDominationThree</Link>
        </li>
        <li>
          <Link to="/chinesedominationtwo">ChineseDominationTwo</Link>
        </li>
        <li>
          <Link to="/after1945five">After1945Five</Link>
        </li>
        <li>
          <Link to="/chinesedominationfour">ChineseDominationFour</Link>
        </li>
        <li>
          <Link to="/frenchdominationthree">FrenchDominationThree</Link>
        </li>
        <li>
          <Link to="/home1">Home1</Link>
        </li>
        <li>
          <Link to="/after1945two">After1945Two</Link>
        </li>
        <li>
          <Link to="/precis">Precis</Link>
        </li>
        <li>
          <Link to="/independencefour">IndependenceFour</Link>
        </li>
        <li>
          <Link to="/after1945four">After1945Four</Link>
        </li>
        <li>
          <Link to="/after1945three">After1945Three</Link>
        </li>
        <li>
          <Link to="/resources">Resources</Link>
        </li>
        <li>
          <Link to="/protohistorytwo">ProtohistoryTwo</Link>
        </li>
        <li>
          <Link to="/protohistoryone">ProtohistoryOne</Link>
        </li>
        <li>
          <Link to="/prehistoricone">PrehistoricOne</Link>
        </li>
      </ul>
    </div>
  );
};

export default Home;
